version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      - FLASK_HOST=0.0.0.0
      # Provide your API keys here
      # - VT_API_KEY=
      # - SECURITYTRAILS_API_KEY=
      # - SHODAN_API_KEY=
    volumes:
      - ./:/app:z
